:sparkles: affichage capacite page detail
Symbol-it/unicorn-front-nuxt pull request #6
Opened 2022-04-08 14:05 UTC by K-Hournont

2022-04-12 13:55 UTC, lhenocq requested changes

2022-04-12 13:55 UTC, lhenocq commented on pages/_id.vue
> +          <ul class="unicorn__details">
v-if="unicorn.capacities"

2022-04-12 13:55 UTC, lhenocq commented on pages/_id.vue
> +             <progress class="unicorn__details__progress-bar" max="100" :value="Math.random() * 100 + 50"/>
quel est l'objet de cette balise progress ?

2022-04-12 15:23 UTC, K-Hournont commented on pages/_id.vue
> +             <progress class="unicorn__details__progress-bar" max="100" :value="Math.random() * 100 + 50"/>
je trouvais ca plus interessant d'afficher les capacités avec une progress bar (même si la value est random) au lieu de juste refaire une liste

2022-04-13 15:23 UTC, lhenocq approved these changes

2022-04-13 15:27 UTC, DelphineLods approved these changes

2022-04-13 15:27 UTC, merged

2022-04-13 15:27 UTC, lhenocq approved these changes